### ISSUE TITLE
Bower の競合について

### ISSUE THREAD

**Issue by petamoriken** [1000ch/position-sticky#2]
`bower i position-sticky` をした際に、別の方のライブラリがダウンロードされてしまいます。
もしよろしければ、独自の名前で Bower に登録していただけませんか？

**Comment by 1000ch** [comment]
ご報告ありがとうございます。
今のところいい名前が浮かんでいないので、一旦以下でダウンロードお願いできますか？

``` sh
$ bower i 1000ch/position-sticky
```

**Comment by petamoriken** [comment]
了解しました。
ありがとうございます。
